tukimiMypage/tukimiMypage/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('tukimipage/', include('tukimipage.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/tukimipage/')),
]

tukimiMypage/tukimipage/urls.py
from django.urls import path
from .import views

app_name = 'tukimipage'

urlpatterns = [
    path('', views.default, name='default'),
    path('programlist',views.programlist, name='programlist'),
    path('index', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
]

tukimiMypage/tukimipage/models.py
from django.db import models

class Article(models.Model):
    content = models.CharField(max_length=200)
    user_name = models.CharField(max_length=200,null = True)

    def __str__(self):
        return self.content

tukimiMypage/tukimipage/forms.py
from django import forms
from .models import Article

class SearchForm(forms.Form):
        keyword = forms.CharField(label='検索', max_length=100)

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('content', 'user_name')

tukimiMypage/tukimipage/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article
from .forms import SearchForm
from .forms import ArticleForm

#デフォルトページ
def default(request):
    return render(request, 'tukimipage/default.html')

#プログラミング一覧ページ
def programlist(request):
    return render(request, 'tukimipage/programList.html')

#デフォルト関数
def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        articles = Article.objects.filter(content__contains=keyword)
    else:
        searchForm = SearchForm()
        articles = Article.objects.all()

    context = {
        'message': '掲示板',
        'articles': articles,
        'searchForm': searchForm,
    }
    return render(request, 'tukimipage/index.html', context)

#詳細ページ関数
def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    context ={
        'massage': 'show Article' + str(id),
        'article': article,
    }
    return render(request, 'tukimipage/detail.html',context)

#新規作成ページ関数
def new(request):
    articleForm = ArticleForm()

    context = {
        'message': 'New Article',
        'articleForm': articleForm,
    }
    return render(request, 'tukimipage/new.html', context)

#編集ページ関数
def edit(request, id):
    article = get_object_or_404(Article, pk=id)
    articleForm = ArticleForm(instance=article)

    context = {
        'message': 'Edit Article',
        'article': article,
        'articleForm': articleForm,
    }
    return render(request, 'tukimipage/edit.html', context)

#アップデートページ関数
def update(request, id):
    if request.method == 'POST':
        article = get_object_or_404(Article, pk=id)
        articleForm = ArticleForm(request.POST, instance=article)
        if articleForm.is_valid():
            articleForm.save()

    context = {
        'message': 'Update article ' + str(id),
        'article': article,
    }
    return render(request, 'tukimipage/detail.html', context)

#作成ページ関数
def create(request):
    if request.method == 'POST':
        articleForm = ArticleForm(request.POST)
        if articleForm.is_valid():
            article = articleForm.save()

    context = {
        'message': 'Create article ' + str(article.id),
        'article': article,
    }
    return render(request, 'tukimipage/detail.html', context)

#削除ページ関数
def delete(request, id):
    article = get_object_or_404(Article, pk=id)
    article.delete()

    articles = Article.objects.all()
    context = {
        'message': 'Delete article ' + str(id),
        'articles': articles,
    }
    return render(request, 'tukimipage/index.html', context)

tukimiMypage/tukimipage/templates/tukimipage/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>つきみ保管庫</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <style>
        body {
            padding-top: 80px;
        }
    </style>
</head>

<body>

    <div class="container">
        <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "tukimipage:default" %}'>つきみ日常保管庫</a>

            <a class='navbar-brand ' style="padding: left 2rem;;" href='{% url "tukimipage:default" %}'>Home</a>

            <a class='navbar-brand ' style="padding: left 2rem;;" href='{% url "tukimipage:programlist" %}'>成果物一覧</a>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <nav class='navbar navbar-expand-md navbar-dark bg-secondary fixed-bottom'>
    </nav>
</body>

</html>

tukimiMypage/tukimipage/templates/tukimipage/default.html
{% extends './base.html'%}
{% block content %}

<div class="container">
    <div class="starter-template">
        <div class="jumbotron text-center centering-title">
            <h1 class="display-2" style="display:inline-block;">Welcome to</h1>
            <br>
            <h1 class="display-2" style="display:inline-block;">つきみ</h1>
            <h1 class="display-2" style="display:inline-block;">日常</h1>
            <h1 class="display-2" style="display:inline-block;">保管庫</h1>

        </div>
    </div>


    <h1 style="padding-bottom: 2rem; padding-left: 3rem;">自己紹介</h1>
    <table class="table table-striped table-hover">
        <tr>
            <td>名前:</td>
            <td>つきみ</td>
        </tr>
        <tr>
            <td>プロフィール:</td>
            <td>
                プロフィール:愛知県出身で現在19歳の専門1年です。ネットではつきみという名前で活動しています。
                <br>のんびり好きなこと興味があることを色々やっています。フレンドリーなので声をかけてくれると嬉しいです。
            </td>
        </tr>
        <tr>
            <td>これまで使ったことある言語:</td>
            <td>HTML5,Javascript,CSS,python,C#,java,SQL</td>
        </tr>
        <tr>
            <td>好きな食べ物。好きなこと:</td>
            <td>雪見だいふく。お寿司。物を作ったりするのが好き。特に制作過程が一番やりがいを感じる人</td>
        </tr>
    </table>

    <h1 style="padding-bottom: 2rem; padding-left: 3rem;">このサイトの目的</h1>
    <table class="table table-striped table-hover">
        <tr>
            <td>
                自分が作った作成物や自分自身が感じたことや共有したいことなどを投稿していくサイトです。
            </td>
        </tr>
    </table>
</div>

</div>

{% endblock %}

tukimiMypage/tukimipage/templates/tukimipage/detail.html
{% extends './base.html'%}
{% block content %}

<div class="container">
    <p>{{ message }}</p>
    <p>{{ article.content }}, {{ article.user_name }}</p>
    <div>
        <a href='{% url "tukimipage:index" %}' class='btn btn-outline-primary'>一覧</a>
        <a href='{% url "tukimipage:edit" article.id %}' class='btn btn-outline-primary'>編集</a>
        <a href='{% url "tukimipage:delete" article.id %}' class='btn btn-outline-secondary'>削除</a>
    </div>
</div>
{% endblock %}

tukimiMypage/tukimipage/templates/tukimipage/edit.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>{{ message }}</h1>

    <form action='{% url "tukimipage:update" article.id %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form articleForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>保存する</button>
        <a href='{% url "tukimipage:detail" article.id %}' class='btn btn-outline-secondary'>戻る</a>
    </form>
</div>
{% endblock %}

tukimiMypage/tukimipage/templates/tukimipage/index.html
{% extends './base.html'%}
{% block content %}

<div class="container">
    <p>{{ message }}</p>

    {% if searchForm %}
    <form action='{% url "tukimipage:index" %}' method='get'>
        <div class='form-group'>
            {{ searchForm }}
            <input type="submit" class="btn btn-outline-primary" value="OK" />
            <a href="{% url 'tukimipage:index' %}" class="btn btn-outline-secondary">クリア</a>
        </div>
    </form>
    {% endif %}

    <table class='table table-striped table-hover'>
        {% for article in articles %}
        <tr>
            <td>{{ article.content }}</td>
            <td>{{ article.user_name }}</td>
            <td>
                <a href='{% url "tukimipage:detail" article.id %}' class='btn btn-outline-primary'>詳細</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div>
        <a href='{% url "tukimipage:new" %}' class='btn btn-outline-primary'>新規</a>
    </div>
</div>
{% endblock %}

tukimiMypage/tukimipage/templates/tukimipage/new.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>{{ message }}</h1>

    <form action='{% url "tukimipage:create" %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form articleForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>作成する</button>
        <a href='{% url "tukimipage:index" %}' class='btn btn-outline-secondary'>戻る</a>
    </form>
</div>
{% endblock %}

tukimiMypage/tukimipage/templates/tukimipage/programList.html
{% extends './base.html'%}
{% block content %}

<div class="container">
    <h1>成果物一覧</h1>
    <table class='table table-striped table-hover'>
        <tr>
            <td>日にち</td>
            <td>作成物</td>
            <td>URL</td>
        </tr>
        <tr>
            <td>2024/01/25</td>
            <td>掲示板サイト</td>
            <td><a href='{% url "tukimipage:index" %}'>URL</a></td>
        </tr>
        <tr>
            <td>2022/08/15</td>
            <td>ウマ娘育成計算</td>
            <td><a href="https://tukimi1215.github.io/umamusume/">URL</a></td>
        </tr>
        <tr>
            <td>2023/11/12</td>
            <td>googleChome-CRloader</td>
            <td><a href="https://github.com/Tukimi1215/googleChome-CRloader">GitHubURL</a></td>
        </tr>
    </table>
</div>
{% endblock %}